###
GET http://example.com
###
GET http://example.com
###
GET http://example.com/api/
Content-Type: application/json
Accept: application/json

###
POST http://example.com
Content-Type: multipart/form-data
abc
< content.json
def

###
