###
GET http://example.com
###
GET http://example.com
###
GET http://example.com/api/
Content-Type: application/json
Accept: application/json

###
POST http://example.com

abc
< content.json
def

###
